// <auto-generated />
using System;
using KeyboardShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyboardShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251013010838_CartAndOrders")]
    partial class CartAndOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KeyboardShop.Models.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Connectivity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SwitchType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Keyboards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Vortex",
                            Connectivity = "Wired",
                            ImageFile = "vortex75.jpg",
                            Layout = "75%",
                            Name = "Vortex 75 Pro",
                            Price = 169m,
                            Slug = "vortex-75-pro",
                            SwitchType = "Linear"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Keychron",
                            Connectivity = "Wireless",
                            ImageFile = "k2.jpg",
                            Layout = "75%",
                            Name = "Keychron K2",
                            Price = 89m,
                            Slug = "keychron-k2",
                            SwitchType = "Tactile"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ducky",
                            Connectivity = "Wired",
                            ImageFile = "ducky_tkl.jpg",
                            Layout = "TKL",
                            Name = "Ducky One 2 TKL",
                            Price = 119m,
                            Slug = "ducky-one-2-tkl",
                            SwitchType = "Clicky"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Akko",
                            Connectivity = "Wireless",
                            ImageFile = "akko3068b.jpg",
                            Layout = "65%",
                            Name = "Akko 3068B",
                            Price = 99m,
                            Slug = "akko-3068b",
                            SwitchType = "Linear"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Leopold",
                            Connectivity = "Wired",
                            ImageFile = "fc660m.jpg",
                            Layout = "65%",
                            Name = "Leopold FC660M",
                            Price = 139m,
                            Slug = "leopold-fc660m",
                            SwitchType = "Tactile"
                        });
                });

            modelBuilder.Entity("KeyboardShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KeyboardShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KeyboardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KeyboardShop.Models.OrderItem", b =>
                {
                    b.HasOne("KeyboardShop.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KeyboardShop.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
